[project]
name = "volunteer-scheduling"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pydantic>=2.13.5",
    "pyyaml>=6.0.3",
]

[project.scripts]
volunteer-scheduling = "volunteer_scheduling.main:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
source-include = ["volunteer_scheduling/**"]
